import Footer from "../components/layout/Footer";
import Header from "../components/layout/Header";
import "./globals.css";
import { Cantarell } from "next/font/google";

export const metadata = {
  title: "Audioshots",
  description: "Generated by Weoto",
};

const audio = Cantarell({
  weight: "400",
  subsets: ["latin"],
  preload: true,
  });

export default function RootLayout({ children }) {
  return (
    <html className={audio.className} lang="en">
      <body className={audio.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
